### ISSUE TITLE
Vault can't keep a leader

### ISSUE THREAD

**Issue by rhoml** [hashicorp/vault#1184]
We are running Vault v0.5.1 and we are hitting an odd problem, it doesn't seem to keep a leader even when there is only one Vault in the cluster. It keeps itself as standby mode, and eventually gets a leader ip address.

``` 
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
        Mode: standby
        Leader: <none>
```

Any idea of what can be happening there? We are using consul backend. And abviously I can't execute most of the commands

```
$: vault auth -methods
Error reading auth table: redirect would cause protocol downgrade
```

**Comment by rhoml** [comment]
Closing the issue, this happens when the advertiser_addr is not using SSL.

**Comment by rhoml** [comment]
Re-opening again since I've stopped one of my vaults and the issue occurs again

**Comment by jefferai** [comment]
Hi @rhoml ,

Without logs and your configuration I can't tell you much. If you can paste those in that would be very helpful.

Thanks!

**Comment by rhoml** [comment]
Never mind, ghosts on the internet everything is working properly now. What I found intriguing is that logs never shoed anything.

**Comment by jefferai** [comment]
It's possible they did and it just wasn't clear to you. Since they were never posted, can't really analyze them  :-)

**Comment by rhoml** [comment]
next time =)

**Comment by emk** [comment]
@jefferai I have reproed this with an etcd backend in a three-machine cluster. Here's the log, with the actual hostnames replaced with `example.com`:

```
$ env VAULT_ADDR=https://vault1.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://vault1.example.com:8200/
$ env VAULT_ADDR=https://vault2.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: <none>
$ env VAULT_ADDR=https://vault3.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: <none>
```

If the leader falls over, neither of the standbys will reliably pick up leadership; they just sit there. Here's a log with expirations and other clutter filtered out:

```
May 20 05:26:47 192.168.1.1 logger:  /ecs-vault-a-22-vault-cabcbdaed7829cee2600 	status code: 404, request id: 1eca3cbe-1e86-11e6-a813-d3092ea6021a
May 20 09:03:52 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:52 [WARN] core: leadership lost, stopping active operation
May 20 09:03:52 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:52 [INFO] core: pre-seal teardown starting
May 20 09:03:52 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:52 [INFO] rollback: stopping rollback manager
May 20 09:03:52 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:52 [INFO] core: pre-seal teardown complete
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: acquired lock, enabling active operation
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: post-unseal setup starting
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type generic at secret/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type system at sys/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type ssh at ssh/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] core: mounted backend of type aws at aws/
May 20 09:03:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:03:53 [INFO] rollback: starting rollback manager
May 20 09:04:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:04:37 [INFO] core: post-unseal setup complete
May 20 09:44:19 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:19 [WARN] core: leadership lost, stopping active operation
May 20 09:44:19 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:19 [INFO] core: pre-seal teardown starting
May 20 09:44:19 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:19 [INFO] rollback: stopping rollback manager
May 20 09:44:19 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:19 [INFO] core: pre-seal teardown complete
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: acquired lock, enabling active operation
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: post-unseal setup starting
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type generic at secret/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type system at sys/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type ssh at ssh/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] core: mounted backend of type aws at aws/
May 20 09:44:21 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:44:21 [INFO] rollback: starting rollback manager
May 20 09:45:06 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:45:06 [INFO] core: post-unseal setup complete
May 20 09:59:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:26 [WARN] core: leadership lost, stopping active operation
May 20 09:59:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:26 [INFO] core: pre-seal teardown starting
May 20 09:59:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:26 [INFO] rollback: stopping rollback manager
May 20 09:59:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:26 [INFO] core: pre-seal teardown complete
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: acquired lock, enabling active operation
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: post-unseal setup starting
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type generic at secret/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type system at sys/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type ssh at ssh/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] core: mounted backend of type aws at aws/
May 20 09:59:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 16:59:28 [INFO] rollback: starting rollback manager
May 20 10:00:13 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:00:13 [INFO] core: post-unseal setup complete
May 20 10:51:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:25 [WARN] core: leadership lost, stopping active operation
May 20 10:51:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:26 [INFO] core: pre-seal teardown starting
May 20 10:51:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:26 [INFO] rollback: stopping rollback manager
May 20 10:51:26 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:26 [INFO] core: pre-seal teardown complete
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: acquired lock, enabling active operation
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: post-unseal setup starting
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type generic at secret/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type system at sys/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type ssh at ssh/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] core: mounted backend of type aws at aws/
May 20 10:51:28 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:51:28 [INFO] rollback: starting rollback manager
May 20 10:52:11 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 17:52:11 [INFO] core: post-unseal setup complete
May 20 12:08:31 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:31 [WARN] core: leadership lost, stopping active operation
May 20 12:08:31 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:31 [INFO] core: pre-seal teardown starting
May 20 12:08:31 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:31 [INFO] rollback: stopping rollback manager
May 20 12:08:31 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:31 [INFO] core: pre-seal teardown complete
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: acquired lock, enabling active operation
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: post-unseal setup starting
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type generic at secret/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type system at sys/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type ssh at ssh/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] core: mounted backend of type aws at aws/
May 20 12:08:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:08:36 [INFO] rollback: starting rollback manager
May 20 12:09:19 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 19:09:19 [INFO] core: post-unseal setup complete
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [WARN] core: leadership lost, stopping active operation
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [INFO] core: pre-seal teardown starting
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [INFO] rollback: stopping rollback manager
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [INFO] core: pre-seal teardown complete
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [INFO] core: acquired lock, enabling active operation
May 20 13:24:04 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:04 [INFO] core: post-unseal setup starting
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type generic at secret/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type system at sys/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type ssh at ssh/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] core: mounted backend of type aws at aws/
May 20 13:24:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:05 [INFO] rollback: starting rollback manager
May 20 13:24:53 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 20:24:53 [INFO] core: post-unseal setup complete
May 20 15:25:34 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:34 [WARN] core: leadership lost, stopping active operation
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: pre-seal teardown starting
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] rollback: stopping rollback manager
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: pre-seal teardown complete
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: acquired lock, enabling active operation
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: post-unseal setup starting
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type generic at secret/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type system at sys/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type ssh at ssh/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] core: mounted backend of type aws at aws/
May 20 15:25:35 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:25:35 [INFO] rollback: starting rollback manager
May 20 15:26:23 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/20 22:26:23 [INFO] core: post-unseal setup complete
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:09 [WARN] core: leadership lost, stopping active operation
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: pre-seal teardown starting
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] rollback: stopping rollback manager
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: pre-seal teardown complete
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: acquired lock, enabling active operation
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: post-unseal setup starting
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type generic at secret/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type system at sys/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type ssh at ssh/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] core: mounted backend of type aws at aws/
May 20 20:20:10 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:20:10 [INFO] rollback: starting rollback manager
May 20 20:21:00 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 03:21:00 [INFO] core: post-unseal setup complete
May 20 21:42:36 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:36 [WARN] core: leadership lost, stopping active operation
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:36 [INFO] core: pre-seal teardown starting
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:36 [INFO] rollback: stopping rollback manager
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:36 [INFO] core: pre-seal teardown complete
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: acquired lock, enabling active operation
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: post-unseal setup starting
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type generic at secret/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type system at sys/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type ssh at ssh/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] core: mounted backend of type aws at aws/
May 20 21:42:37 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:42:37 [INFO] rollback: starting rollback manager
May 20 21:43:24 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 04:43:24 [INFO] core: post-unseal setup complete
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [WARN] core: leadership lost, stopping active operation
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: pre-seal teardown starting
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] rollback: stopping rollback manager
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: pre-seal teardown complete
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: acquired lock, enabling active operation
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: post-unseal setup starting
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type generic at secret/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type system at sys/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type postgresql at postgresql/staging/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type postgresql at postgresql/production/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type ssh at ssh/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] core: mounted backend of type aws at aws/
May 20 23:49:20 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:49:20 [INFO] rollback: starting rollback manager
May 20 23:50:05 192.168.1.2 logger:  /ecs-vault-b-16-vault-ea9dfcf0fcd6f9c0e701 2016/05/21 06:50:05 [INFO] core: post-unseal setup complete
May 21 02:02:02 192.168.1.1 logger:  /ecs-vault-a-22-vault-cabcbdaed7829cee2600 2016/05/21 09:02:02 [WARN] core: leadership lost, stopping active operation
May 21 02:02:02 192.168.1.1 logger:  /ecs-vault-a-22-vault-cabcbdaed7829cee2600 2016/05/21 09:02:02 [INFO] core: pre-seal teardown starting
May 21 02:02:02 192.168.1.1 logger:  /ecs-vault-a-22-vault-cabcbdaed7829cee2600 2016/05/21 09:02:02 [INFO] rollback: stopping rollback manager
May 21 02:02:02 192.168.1.1 logger:  /ecs-vault-a-22-vault-cabcbdaed7829cee2600 2016/05/21 09:02:02 [INFO] core: pre-seal teardown complete
```

Our config file looks like:

```
backend "s3" {
  bucket = "out-vault-bucket"
  # These keys are added by ./start_server.
  access_key = "@access_key@"
  secret_key = "@secret_key@"
  region = "us-east-1"
}

ha_backend "etcd" {
  address = "https://aws-us-east-1-portal.16.dblayer.com:123,https://aws-us-east-1-portal.15.dblayer.com:124"
  advertise_addr = "https://@advertise_addr@:8200/"
  # Needed to work with compose.io.  See
  # https://github.com/hashicorp/vault/pull/921 for details.
  sync = "no"
  username = "root"
  password = "@etcd_password@"
  tls_ca_file = "/app/etcd-ca.pem"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/data/ssl/combined.crt"
  tls_key_file = "/data/ssl/cert.key"
}
```

We're running v0.4.0-1182-ga74332b, which is a recentish 5.something master branch.

**Comment by seamusabshere** [comment]
@emk did this happen on previous versions?

**Comment by emk** [comment]
On an earlier 5.something build as well, IIRC. Don't remember it on older releases, though those fell over with the S3 issue: #1345.

**Comment by jefferai** [comment]
@emk So you're not using S3 anymore, even though it should be fixed?

**Comment by emk** [comment]
We just saw `Leader: <none>` on the two standby secondaries again this morning, with a crashed primary, but we still don't have any logs much better than what I posted before. I think this is a real thing and probably worth re-opening. Any suggestions for env vars, etc., I could set to get you more useful logs?

**Comment by jefferai** [comment]
@emk If Vault can't keep a leader, I would suggest checking your etcd logs for clues. Without Vault itself logging an error condition, simply "leadership lost", it suggests that there is an issue with the lock itself. Unfortunately, I have not used etcd in a very very long time and don't have much to give you in the way of debugging steps.

**Comment by emk** [comment]
OK, the next time we see this, we'll bug our etcd vendor.

We'd be very interested in a hosted version of Consul, by the way, but the last I looked, I didn't find one. Running a Consul/etcd/ZooKeeper cluster is rather annoying if all we're doing is hosting a single leadership lock.

**Comment by emk** [comment]
Oh, a fun new variation this morning:
```
# vault1
High-Availability Enabled: true
	Mode: active
	Leader: https://vault1.example.com:8200/

# vault2
High-Availability Enabled: true
	Mode: active
	Leader: https://vault2.example.com:8200/

# vault3
High-Availability Enabled: true
	Mode: standby
	Leader: <none>
```
Yup. vault1 and vault2 both think they're the leader, and vault3 can't see any leader.

There's nothing interesting in the etcd logs, as far as I can tell. I wonder if the etcd backend might have issues here?

**Comment by jefferai** [comment]
I honestly don't know. But given that HA coordination is storage-backend-specific, and we've never seen this with Consul, I'm betting on either etcd itself or the etcd storage backend.

**Comment by emk** [comment]
OK, I've reproduced another multiple leader conflict:

```
$ env VAULT_ADDR=https://vault1.example.com:8200/ vault status

Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: https://vault3.example.com:8200/

$ env VAULT_ADDR=https://vault2.example.com:8200/ vault status

Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://vault2.example.com:8200/

$ env VAULT_ADDR=https://vault3.example.com:8200/ vault status

Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://vault3.example.com:8200/
```

The etcd server has one lock key:

```
$ fdyi etcdctl ls /vault/core/_lock
/vault/core/_lock/00000000000000990967
$ etcdctl get /vault/core/_lock/00000000000000990967
0bc5956a-7c6d-2fc9-81e0-94b6b64cd491
```

I think the next steps are for me to read the code more closely, then to add more logging to the etcd backend.

**Comment by emk** [comment]
OK, progress! I've added logging in https://github.com/faradayio/vault-1/commit/6d9ac1129fa942421e506b9552d415eb1ccf0bc5 which may help track this down. My current hypothesis is that one of these two routines might be throwing away an important error:

- [`periodicallyRenewSemaphoreKey`](https://github.com/hashicorp/vault/blob/09151dfff8fee8807998f4a5a881466b0d591164/physical/etcd.go#L413)
- [`watchForKeyRemoval`](https://github.com/hashicorp/vault/blob/09151dfff8fee8807998f4a5a881466b0d591164/physical/etcd.go#L427)

In either case, a transient network error could cause issues for the lock.

At the moment, on a cleanly booted vault cluster with 3 notes, I see:

```
/vault/core/_lock/00000000000000999029
/vault/core/_lock/00000000000000999143
/vault/core/_lock/00000000000000999545
```

When this falls over again, I'll take a look and see what's up in the logs.

**Comment by emk** [comment]
Here's the state as of this morning. It's a pretty classic-looking failure:
```
$ etcdctl ls /vault/core/_lock/
$ env VAULT_ADDR=https://vault1.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://vault1.example.com:8200/
$ env VAULT_ADDR=https://vault2.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: <none>
$ env VAULT_ADDR=https://vault3.example.com:8200/ vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://vault3.example.com:8200/
```
Logs for vault1 (just the interesting bits):
```
==> Vault server configuration:

              HA Backend: etcd
       Advertise Address: https://vault1.example.com:8200/
                 Backend: s3
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Version: Vault v0.6.0-beta2 ('6d9ac1129fa942421e506b9552d415eb1ccf0bc5+CHANGES')

==> Vault server started! Log data will stream in below:

2016/06/08 20:02:42 [INFO] core: vault is unsealed
2016/06/08 20:02:42 [INFO] core: entering standby mode
2016/06/08 21:39:07 [INFO] core: acquired lock, enabling active operation
2016/06/08 21:39:07 [INFO] core: post-unseal setup starting
2016/06/08 21:39:07 [INFO] core: mounted backend of type generic at secret/
2016/06/08 21:39:07 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/06/08 21:39:07 [INFO] core: mounted backend of type system at sys/
2016/06/08 21:39:07 [INFO] core: mounted backend of type postgresql at postgresql/staging/
2016/06/08 21:39:07 [INFO] core: mounted backend of type postgresql at postgresql/production/
2016/06/08 21:39:07 [INFO] core: mounted backend of type ssh at ssh/
2016/06/08 21:39:07 [INFO] core: mounted backend of type aws at aws/
2016/06/08 21:39:07 [INFO] core: mounted backend of type pki at pki/
2016/06/08 21:39:07 [INFO] rollback: starting rollback manager
2016/06/08 21:39:54 [INFO] expire: restored 1022 leases
2016/06/08 21:39:54 [INFO] core: post-unseal setup complete
2016/06/08 21:53:10 [INFO] expire: revoked 'auth/token/create/14267c65e394a55c7f727a02ef9fe47af5fefc45'
2016/06/08 23:55:58 [INFO] expire: revoked 'aws/sts/ecr-push/8bc93614-f6be-57bc-af3f-440e187fe5d2'
2016/06/08 23:56:33 [INFO] expire: revoked 'auth/token/create/3d5bb7e8c195a8abc47dd2a3dc7b78fd7011b336'
2016/06/09 00:07:02 [INFO] expire: revoked 'auth/token/create/fd4b43dad280991ac99dafe973f4ccfe938285ed'
2016/06/09 00:11:59 [INFO] expire: revoked 'auth/token/create/4b74926245a301de52a369c713a72b837d41daf1'
2016/06/09 00:15:28 [INFO] expire: revoked 'aws/sts/ecr-push/b5d6a4ff-32ff-ce25-9da3-8b6971103d96'
2016/06/09 00:27:28 [INFO] expire: revoked 'aws/sts/ecr-push/f2590fa7-e7b7-c865-9824-c27f97025f3b'
2016/06/09 00:29:41 [INFO] expire: revoked 'aws/sts/ecr-push/cee1db04-78c6-2a2c-6151-e29269cbfd6d'
2016/06/09 00:29:45 [INFO] expire: revoked 'aws/sts/ecr-push/ee616f52-a844-a749-74b6-922c75133995'
2016/06/09 00:30:12 [INFO] expire: revoked 'aws/sts/ecr-push/e204b248-e741-8108-ebc6-67acd78c5148'
2016/06/09 00:37:44 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000000999545: 100: Key not found (/vault/core/_lock/00000000000000999545) [1008726]
2016/06/09 00:37:49 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000000999545: 100: Key not found (/vault/core/_lock/00000000000000999545) [1008728]
```
Logs for vault2:
```
==> Vault server configuration:

              HA Backend: etcd
       Advertise Address: https://vault2.example.com:8200/
                 Backend: s3
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Version: Vault v0.6.0-beta2 ('6d9ac1129fa942421e506b9552d415eb1ccf0bc5+CHANGES')

==> Vault server started! Log data will stream in below:

2016/06/08 19:44:12 [INFO] core: vault is unsealed
2016/06/08 19:44:12 [INFO] core: entering standby mode
2016/06/08 21:39:07 [ERR] core: failed to acquire lock: semaphore key removed before lock aquisition
2016/06/08 21:39:07 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000000999143: 100: Key not found (/vault/core/_lock/00000000000000999143) [1002809]
2016/06/09 06:02:18 http: TLS handshake error from 54.x.y.z:34037: read tcp 172.17.0.4:8200->54.x.y.z:34037: read: connection reset by peer
2016/06/09 07:21:10 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001002814: 100: Key not found (/vault/core/_lock/00000000000001002814) [1017613]
2016/06/09 07:21:15 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001002814: 100: Key not found (/vault/core/_lock/00000000000001002814) [1017614]
2016/06/09 07:21:21 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001002814: 100: Key not found (/vault/core/_lock/00000000000001002814) [1017615]
# ...and so on, for a long time.
```
Logs for vault3:
```
==> Vault server configuration:

              HA Backend: etcd
       Advertise Address: https://vault3.faraday.io:8200/
                 Backend: s3
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Version: Vault v0.6.0-beta2 ('6d9ac1129fa942421e506b9552d415eb1ccf0bc5+CHANGES')

==> Vault server started! Log data will stream in below:

2016/06/08 19:16:26 [INFO] core: vault is unsealed
2016/06/08 19:16:26 [INFO] core: entering standby mode
2016/06/08 19:16:26 [INFO] core: acquired lock, enabling active operation
2016/06/08 19:16:26 [INFO] core: post-unseal setup starting
2016/06/08 19:16:26 [INFO] core: mounted backend of type generic at secret/
2016/06/08 19:16:26 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/06/08 19:16:26 [INFO] core: mounted backend of type system at sys/
2016/06/08 19:16:26 [INFO] core: mounted backend of type postgresql at postgresql/staging/
2016/06/08 19:16:26 [INFO] core: mounted backend of type postgresql at postgresql/production/
2016/06/08 19:16:26 [INFO] core: mounted backend of type ssh at ssh/
2016/06/08 19:16:26 [INFO] core: mounted backend of type aws at aws/
2016/06/08 19:16:26 [INFO] core: mounted backend of type pki at pki/
2016/06/08 19:16:26 [INFO] rollback: starting rollback manager
2016/06/08 19:17:17 [INFO] expire: restored 1022 leases
2016/06/08 19:17:17 [INFO] core: post-unseal setup complete
2016/06/08 19:33:43 [WARN] core: leadership lost, stopping active operation
2016/06/08 19:33:43 [INFO] core: pre-seal teardown starting
2016/06/08 19:33:43 [INFO] rollback: stopping rollback manager
2016/06/08 19:33:43 [INFO] core: pre-seal teardown complete
2016/06/08 19:33:50 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000000998843: 100: Key not found (/vault/core/_lock/00000000000000998843) [999028]
2016/06/08 19:33:51 [INFO] core: acquired lock, enabling active operation
2016/06/08 19:33:51 [INFO] core: mounted backend of type generic at secret/
2016/06/08 19:33:51 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/06/08 19:33:51 [INFO] core: mounted backend of type system at sys/
2016/06/08 19:33:51 [INFO] core: mounted backend of type postgresql at postgresql/staging/
2016/06/08 19:33:51 [INFO] core: mounted backend of type postgresql at postgresql/production/
2016/06/08 19:33:51 [INFO] core: mounted backend of type ssh at ssh/
2016/06/08 19:33:51 [INFO] core: mounted backend of type aws at aws/
2016/06/08 19:33:51 [INFO] core: mounted backend of type pki at pki/
2016/06/08 19:33:51 [INFO] rollback: starting rollback manager
2016/06/08 19:34:36 [INFO] expire: restored 1022 leases
2016/06/08 19:34:36 [INFO] core: post-unseal setup complete
2016/06/08 20:34:37 [INFO] expire: revoked '...'
2016/06/08 21:39:07 [WARN] core: leadership lost, stopping active operation
2016/06/08 21:39:07 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000000999029: 100: Key not found (/vault/core/_lock/00000000000000999029) [1002809]
2016/06/08 21:39:07 [INFO] core: pre-seal teardown starting
2016/06/08 21:39:07 [INFO] rollback: stopping rollback manager
2016/06/08 21:39:07 [INFO] core: pre-seal teardown complete
2016/06/09 00:37:42 [INFO] core: acquired lock, enabling active operation
2016/06/09 00:37:42 [INFO] core: post-unseal setup starting
2016/06/09 00:37:42 [INFO] core: mounted backend of type generic at secret/
2016/06/09 00:37:42 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/06/09 00:37:42 [INFO] core: mounted backend of type system at sys/
2016/06/09 00:37:42 [INFO] core: mounted backend of type postgresql at postgresql/staging/
2016/06/09 00:37:42 [INFO] core: mounted backend of type postgresql at postgresql/production/
2016/06/09 00:37:42 [INFO] core: mounted backend of type ssh at ssh/
2016/06/09 00:37:42 [INFO] core: mounted backend of type aws at aws/
2016/06/09 00:37:42 [INFO] core: mounted backend of type pki at pki/
2016/06/09 00:37:42 [INFO] rollback: starting rollback manager
2016/06/09 00:38:28 [INFO] expire: restored 1022 leases
2016/06/09 00:38:28 [INFO] core: post-unseal setup complete
2016/06/09 02:16:39 [INFO] expire: revoked 'auth/token/create/f48790c6d07d7eed2036f10adcf5360f33939e65'
2016/06/09 06:00:51 http: TLS handshake error from 54.x.y.z:64708: read tcp 172.17.0.4:8200->54.x.y.z:64708: read: connection reset by peer
2016/06/09 06:16:59 http: TLS handshake error from 54.x.y.z:55781: read tcp 172.17.0.4:8200->54.x.y.z:55781: read: connection reset by peer
2016/06/09 07:21:10 [WARN] core: leadership lost, stopping active operation
2016/06/09 07:21:10 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001002810: 100: Key not found (/vault/core/_lock/00000000000001002810) [1017613]
2016/06/09 07:21:10 [INFO] core: pre-seal teardown starting
2016/06/09 07:21:10 [INFO] rollback: stopping rollback manager
2016/06/09 07:21:10 [INFO] core: pre-seal teardown complete
2016/06/09 07:21:11 [INFO] core: acquired lock, enabling active operation
2016/06/09 07:21:11 [INFO] core: post-unseal setup starting
2016/06/09 07:21:11 [INFO] core: mounted backend of type generic at secret/
2016/06/09 07:21:11 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/06/09 07:21:11 [INFO] core: mounted backend of type system at sys/
2016/06/09 07:21:11 [INFO] core: mounted backend of type postgresql at postgresql/staging/
2016/06/09 07:21:11 [INFO] core: mounted backend of type postgresql at postgresql/production/
2016/06/09 07:21:11 [INFO] core: mounted backend of type ssh at ssh/
2016/06/09 07:21:11 [INFO] core: mounted backend of type aws at aws/
2016/06/09 07:21:11 [INFO] core: mounted backend of type pki at pki/
2016/06/09 07:21:11 [INFO] rollback: starting rollback manager
2016/06/09 07:22:08 [INFO] expire: restored 1022 leases
2016/06/09 07:22:08 [INFO] core: post-unseal setup complete
2016/06/09 07:55:11 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001017614: 100: Key not found (/vault/core/_lock/00000000000001017614) [1017992]
2016/06/09 07:55:16 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001017614: 100: Key not found (/vault/core/_lock/00000000000001017614) [1017992]
2016/06/09 07:55:21 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001017614: 100: Key not found (/vault/core/_lock/00000000000001017614) [1017992]
2016/06/09 07:55:27 [ERROR] etcd: couldn't renew key /vault/core/_lock/00000000000001017614: 100: Key not found (/vault/core/_lock/00000000000001017614) [1017992]
# ...etc.
```

**Comment by emk** [comment]
The two relevant bits of code here are:
```go
// renewSemaphoreKey renews an existing semaphore key.
func (c *EtcdLock) renewSemaphoreKey() (string, uint64, error) {
	setOpts := &client.SetOptions{
		TTL:       EtcdLockTTL,
		PrevExist: client.PrevExist,
	}
	response, err := c.kAPI.Set(context.Background(), c.semaphoreKey, c.value, setOpts)
	if err != nil {
		c.logger.Printf("[ERROR] etcd: couldn't renew key %s: %v", c.semaphoreKey, err)
		return "", 0, err
	}
	return response.Node.Key, response.Index, nil
}
```
...and:
```go
// periodically renew our semaphore key so that it doesn't expire
func (c *EtcdLock) periodicallyRenewSemaphoreKey(stopCh chan struct{}) {
	for {
		select {
		case <-time.After(EtcdLockRenewInterval):
			c.renewSemaphoreKey()
		case <-stopCh:
			return
		}
	}
}
```
The lock keys are expiring before the background worker can renew them, and there's no code which notices this. So the lock fails in various strange fashions.

It still bothers me that in the presence of this lock failure, the locking code in `core.go` can conclude that there are two different masters. That's fairly alarming.

**Comment by emk** [comment]
There are two cases that we need to think about:

1. What happens if the key renewal fails during the `for semaphoreKey != currentSemaphoreKey` loop in `Lock`?
2. What happens if the key renewal fails after we return from `Lock`?

We could fix (2) by modifying `periodicallyRenewSemaphoreKey` to look like this:
```go
		case <-time.After(EtcdLockRenewInterval):
			if _, _, err := c.renewSemaphoreKey(); err != nil {
				close(stopCh)
			}
```
But maybe `watchForKeyRemoval` already handles the case where we've returned from `Lock`?

Anyway, I hope this is enough to provide some clues as to what's going on. I need to work on some other stuff today, but maybe I can get back to this sometime next week if that helps.

**Comment by jefferai** [comment]
> It still bothers me that in the presence of this lock failure, the locking code in core.go can conclude that there are two different masters. That's fairly alarming.

Given that the entire purpose of the lock is to indicate which node is the active node, it seems entirely appropriate. What would you suggest here?

**Comment by emk** [comment]
@jefferai I was kinda hoping that when the lock failed that `core` would conclude that something strange was going on and move back to standby. But obviously that depends on how badly the etcd locking code fails—core can't protect against itself outright lies from the lock, obviously.

As for a fix, I don't understand all the issues yet. I suspect that the best move is to carefully audit the etcd `Lock` function to make sure that it fails correctly when `semaphoreKey` for the current process goes away. Clearly `periodicallyRenewSemaphoreKey` is sticking around try to revive a long-dead `semaphoreKey`. But I'm not quite sure what the main thread is doing when that happens. I can probably look at it next week, with any luck.

**Comment by jefferai** [comment]
When the lock fails the code in core will run through the process of giving up leadership and transitioning back to standby. Where you might see a problem is if the next time that the core checks to see if it's acquired the lock it's told "yes". If so, it will then go through the process of becoming the active node. As you said, it can't protect itself against outright lies :-)

**Comment by sgujrati16** [comment]
@emk were you able to figure it out? We are running 3 vault nodes backed by etcd in prod. This evening, we noticed two of the vault nodes were reporting active. Vault nodes are behind ELB and ELB forwards to only the leader. Now, since there are two leaders, ELB is round robining between two leaders. We mostly use Vault for reading secrets, so we are not facing a major issue. But this is something to worry about.

**Comment by emk** [comment]
Yes, we've seen both multiple leaders and no leaders. Etcd HA is badly broken as far as I can tell.

This has really been killing our vault deploy, and it caused us some moderately unpleasant emergencies over the weekend. I'm deeply suspicious of [`periodicallyRenewSemaphoreKey`]( https://github.com/hashicorp/vault/blob/1970ad74d7fec5de7aee4798709d402e86c1e926/physical/etcd.go#L416-L426) and the way it throws away semaphore renewal failures silently. I'm also suspicious about [the fact that this block here happens before the `watchForKeyRemoval` handler gets installed](https://github.com/hashicorp/vault/blob/1970ad74d7fec5de7aee4798709d402e86c1e926/physical/etcd.go#L522-L556). Some combination of these is causing keys to silently expire while waiting to take the lock, with dubious consequences.

After carefully weighing our options, we took our vault cluster out of HA mode entirely and we're restarting it manually for a few days as needed. I'm working on an `HABackend` implementation for a single Redis server here: https://github.com/faradayio/vault-1/tree/redis_ha I'll be testing this tomorrow morning on an actual cluster and trying to break it.

At this point, administering a Consul cluster for a single leader election lock is overkill, and we've been burnt too many times by the etcd backend. But we've also seen enough vault server restarts (~1/week with the S3 backend and etcd HA) that we don't want to turn off HA mode completely. So we're going to see what happens if we just do leader elections via Redis. Our Redis server has excellent uptime (better than what we've been seeing with vault), and our Redis will restart automatically if it fails. I'm trying to write the Redis backend to handle this case by having all servers go to standby until Redis comes back.

At this point, I'd honestly recommend people to either use Consul for all backend functionality, or to hold off on deploying vault in production altogether.

**Comment by emk** [comment]
Here's our internal WIP branch for the Redis support: https://github.com/faradayio/vault-1/pull/1 After we test this, if we like the results, we'd be happy to propose it upstream. I was hoping that writing this would give me enough insight into the etcd backend to be able to submit a fix for #1184, but the design issues involved are somewhat different.

**Comment by sgujrati16** [comment]
Thanks for all the details @emk 
I am also trying to look into etcd backend implementation. So far, we have't seen a "no leader" scenario.

**Comment by jefferai** [comment]
@emk It seems very unfair to recommend holding off deploying Vault in production when your issues are fully traceable to your use of an (officially) unsupported HA backend. Plenty of Vault users are running other HA backends with zero problems.

**Comment by sgujrati16** [comment]
I think he meant to hold off Vault deployment with etcd. I know people are using it in prod with DynamoBD (with known HA issues) and with Consul. We started with DynamoDB, but because of its HA issues, we switched to etcd  (our infrastructure is coreos based and we have enough operational expertise in etcd).

**Comment by jefferai** [comment]
@sgujrati16 keep in mind that you can have separate backends for data storage and HA coordination. If you like your data in Dynamo you can keep it there but use etcd (or Consul, or ZK) for HA.

**Comment by sgujrati16** [comment]
Thanks @jefferai. We will try different configuration. In the meantime, we will continue to watch for any potential issues. So far (it has been running for last 10 days), other than multiple leader issue (this didn't block us though), we didn't find any other blocker issue.

**Comment by jefferai** [comment]
@sgujrati16 Multiple leaders is a really really bad state to be in, even if you don't see any obvious issues it's causing right now. It will at some point -- I guarantee it.

**Comment by sgujrati16** [comment]
@jefferai When we figured it out, we made one of the active nodes to step down, and since then, there is just 1 leader. We are keeping a close eye on it. Thanks

**Comment by sgujrati16** [comment]
We are running Vault nodes in docker containers. Does it make sense to have a background process in the container which periodically calls step-down API? Off course, there are issues related to obtaining tokens with proper permissions to do so.

**Comment by jefferai** [comment]
Not really, but if that avoids etcd problems for you...maybe?  :-)

**Comment by sgujrati16** [comment]
We will try and post our observation here.

**Comment by jefferai** [comment]
@emk We've discussed internally and would not merge a Redis HA backend. Just wanted to give a heads up in case that affects how much effort you're willing to spend.

**Comment by emk** [comment]
@jefferai I want to clarify my remarks about production vault use in case anybody misunderstood:

> At this point, I'd honestly recommend people to either use Consul for all backend functionality, or to hold off on deploying vault in production altogether.

This was intended as an either/or:

1. Either use Consul, because it is supported. (It sounds like ZK would also be fine.)
2. Or if you can't use Consul (for whatever reason), and you would need to use the etcd backend for HA for some reason, I would recommend against using vault altogether at the current time. 

When running the S3 backend + etcd HA backend, vault still crashes roughly once per week per server for us (which wouldn't be a big deal if HA worked well), and the etcd backend typically goes into a "multiple leader" mode within 12 hours for us. Sorry if I sounded frustrated in my last comment, but we're not in a great place right now.

All of this worked much better half a year ago when we first deployed vault, but I don't think that the increase in crashes is actually caused by a vault code change—I think that our hosted etcd server is suffering transient network connection problems or perhaps something else has changed in the environment. This has caused an underlying `EctdLock` bug to trigger constantly. I strongly suspect that `periodicallyRenewSemaphoreKey` and `Lock` have issues that trigger when a transient network error prevents the TTL from being bumped while waiting in standby mode.

ACK on you never accepting the Redis lock support. We understand that we'll be maintaining a fork.

**Comment by seamusabshere** [comment]
@jefferai it seems unfair to rule out merging code (1) before you've seen it (2) without allowing for argument

**Comment by emk** [comment]
@seamusabshere Let's discuss Redis later when I at least have proven code, and not further on this bug.

**Comment by sgujrati16** [comment]
@jefferai we are trying to use Consul. We do not have operational expertise in Consul. I have few quick questions and would appreciate any help:

1. From the documentation, it seems that we just need to run agents in Server mode. Is this correct?
2. Link to any documentation or github discussions etc which discuss using Vault with Consul?

Thanks
Sumeet

**Comment by rhoml** [comment]
You can check my puppet-vault module it is self-explanatory vault doc needs a bit of polishing

**Comment by jefferai** [comment]
@emk 

Sorry to hear about your troubles. I do wonder whether the level of effort required to track down/fix the etcd bug would be less than that required to write an entire Redis HA backend.

It's interesting that you're still seeing all of these crashes with S3, as the previous backtrace you posted had a clear cause that should have been addressed by the patch that went in for 0.6. However, it's also entirely possible that it's due to some pathological state in Vault caused by the etcd HA backend lying about its lock state.

I do want to note that there's a difference between simply returning 500s and panicing with a stack trace. The latter is *always* a bug -- even if the alternative, when fixed, is to simple log/return an error. If you're still seeing panics, please open a new GH issue for them!

**Comment by emk** [comment]
Will do! And thank you for fixing that first S3 bug, that made a huge difference.

We're actually running our prototype Redis backend in production right now, and our vault cluster is now back online and ticking nicely with no cluster-wide failures or mutiple leaders, and it has survived some manual "chaos monkey"-style testing. Your unit tests for `Backend` and `HABackend` were excellent and very helpful. (Our Redis backend isn't a true HA backend at this point, because it goes to standby if Redis fails, but we'll probably upgrade it to handle true distributed locks at some point.)

So now we have time to breathe and to take a look at why individual vault instances were crashing (if they still are). This may take a week or two before we know whether there's a problem and to have more data for you. We'll keep you informed, and thank you for all your help!

**Comment by jefferai** [comment]
That all sounds great.

By the by, if you think there's a really good story around Redis HA, I'm willing to take a look and potentially go to bat internally for it -- I'd prefer some high level details rather than looking at code. I think that a number of people internally have been bitten by Redis problems in the past, so it would take a lot of convincing that it's stable, but progress marches on and it's possible that with newer functionality and/or fixes Redis has become a decent candidate.

**Comment by jefferai** [comment]
I'm going to close this now as it's moved on quite a bit from the original post and its issues. Please open a new issue for any further troubles or for any Redis discussion.

Thanks!
