### ISSUE TITLE
Vault UI "Generate credentials" functionality should instead be called "Get credentials" for static database roles

### ISSUE THREAD

**Issue by Berciq** [hashicorp/vault#11973]
**Describe the bug**
The database plugin allows for creating static and dynamic roles. For both types of roles the Vault UI has a "Generate credentials" option. This makes sense for a dynamic database role, because new credentials are, in fact, generated each time this option is used. But the name of this option is misleading for a static role, since Vault UI will display the existing credentials upon selecting this option. What is more, Vault UI displays a warning message when selecting "Generate credentials" that says: "You will not be able to access these credentials later, so please copy them now." But this is only true for a dynamic role and not for a static role. The warning message should not be displayed for the static role, since the credentials can, in fact, be accessed later.

**To Reproduce**
1. Configure the database secrets engine (e.g. as [described here](https://www.vaultproject.io/docs/secrets/databases/postgresql))
2. Create a static database role as [described here](https://learn.hashicorp.com/tutorials/vault/database-creds-rotation)
3. Open the Vault UI
4. Access the list of database roles
5. Your configured static database role will have an option to "Generate credentials" - which is misleading

**Expected behavior**
For static database roles, the option to "Generate credentials" should instead be called something like "Get credentials".
In addition, for static roles, the page where the credentials are displayed should not show the warning message that says: "You will not be able to access these credentials later, so please copy them now."

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.8.0-dev

**Screenshots:**
![image](https://user-images.githubusercontent.com/15101831/124114370-c3b9f800-da6c-11eb-89b5-48fc1ef499cb.png)
![image](https://user-images.githubusercontent.com/15101831/124114660-1e535400-da6d-11eb-8e5c-d331ddec44d9.png)

**Comment by hsimon-hashicorp** [comment]
Hello! I'm raising this for discussion with our UI team. With the Canada Day and July 4th holidays, it may be next week before I can get in touch with them. I'll be sure to be in touch then. Thank you for this feedback!

**Comment by hsimon-hashicorp** [comment]
Just wanted to follow up - I've raised this issue with our UI team, and we'll be taking an item in an upcoming sprint to address it. I'm not exactly sure when that will be, but it _will_ be worked on. Thanks for your patience!

**Comment by Berciq** [comment]
> Just wanted to follow up - I've raised this issue with our UI team, and we'll be taking an item in an upcoming sprint to address it. I'm not exactly sure when that will be, but it _will_ be worked on. Thanks for your patience!

Thank you, Heather! I'd be happy to contribute to improving the UI in this area as well :)

**Comment by hsimon-hashicorp** [comment]
Hi @Berciq! It looks like this has been fixed with PR https://github.com/hashicorp/vault/pull/12024. Let me know if that addresses your concerns. :)

**Comment by Berciq** [comment]
@hsimon-hashicorp yes, this mostly fixes it. The terminology was changed to "Get credentials". However, I'm still seeing the warning screen after pulling in the most recent changes:

![2021-07-22 09-40-40 (1)](https://user-images.githubusercontent.com/15101831/126605263-0cfe7693-f8d5-4ae4-ade5-e47f7c4ce9f3.gif)

**Comment by Berciq** [comment]
The following PR fixes this: https://github.com/hashicorp/vault/pull/12148

**Comment by hsimon-hashicorp** [comment]
@Berciq Very nice, thank you for catching that and for submitting the PR. :)
