### ISSUE TITLE
RabbitMQ engine connection doesn't work with RabbitMQ versions greater than 3.9.0

### ISSUE THREAD

**Issue by tcpecheanu** [hashicorp/vault#12276]
**Describe the bug**
RabbitMQ engine connection doesn't work with RabbitMQ versions greater than 3.9.0. The latest version that works is 3.8.19.

**To Reproduce**
1. Enable RabbitMQ engine:
```
vault secrets enable -path=rabbitmq_test rabbitmq
```
2. Configure RabbitMQ connection:
```
vault write rabbitmq_test/config/connection \
    connection_uri="http://hostname:15672" \
    username="user" \
    password="password"
```
3. See the output:
```
Error writing data to rabbitmq/config/connection: Error making API request.

URL: PUT https://vault-host:8200/v1/rabbitmq_test/config/connection
Code: 500. Errors:

* 1 error occurred:
	* failed to validate the connection: json: cannot unmarshal array into Go struct field UserInfo.tags of type string
```

**Expected behavior**
```
Success! Data written to: rabbitmq_test/config/connection
```

**Environment:**
*Vault Server Version (retrieve with vault status): 1.8.1
*Vault CLI Version (retrieve with vault version): v1.8.1
*Server Operating System/Architecture: Linux/x86_64
*RabbitMQ Version: 3.9.1
*Erlang Version: 23.3.4.5

Vault server configuration file(s):

```
disable_cache           = true
disable_mlock           = true
ui                      = true

storage "mysql" {
  username              = "user"
  password              = "password"
  database              = "vault"
  address               = "IP:3306"
  ha_enabled            = "true"
  lock_table            = "vault_lock"
  plaintext_connection_allowed = "true"
}

listener "tcp" {
  address               = "0.0.0.0:8200"
  cluster_addr          = "0.0.0.0:8201"
  tls_cert_file         = "/opt/vault/tls/certificate.crt"
  tls_key_file          = "/opt/vault/tls/key.key"
  tls_disable           = "false"
}

cluster_addr            = "https://vault-host1:8201"
api_addr                = "https://vault-host1:8200"
cluster_name            = "vault-host"
```

**Additional context**
Tested on both RabbitMQ 3.9.0 and 3.9.1 versions.

**Comment by pschultz** [comment]
Updating github.com/michaelklishin/rabbit-hole should fix the issue. The latest version supports both comma separated strings as well as arrays: https://github.com/michaelklishin/rabbit-hole/blob/728b3db/users.go#L74

**Comment by michaelklishin** [comment]
The current `rabbit-hole` ref [seems to be from 2019](https://github.com/hashicorp/vault/blob/b368a675955707db4e940da29a1043871a3781b6/go.mod#L130).

The library has been RabbitMQ 3.9-ready for [nine months](https://github.com/michaelklishin/rabbit-hole/pull/168) or so.

**Comment by DejfCold** [comment]
I just want to mention that it's still broken.

Vault 1.8.5
RabbitMQ 3.9.9

**Comment by remilapeyre** [comment]
@hsimon-hashicorp This has been fixed in 1baa173648c931ebbc16a7a04ea323d9720d26c4 and can now be closed.

**Comment by hsimon-hashicorp** [comment]
Thank you, @remilapeyre!
