### ISSUE TITLE
Successful Renew token does not remove spinner

### ISSUE THREAD

**Issue by zerkms** [hashicorp/vault#12486]
**Describe the bug**

In the Vault UI 1.8.2 when you click the `Renew token` in the main menu - it shows the spinner. The problem is that the spinner spins forever even though the backend request successfully completed and returned HTTP 200.

**To Reproduce**

1. Open the UI
2. Open the browser dev tools
3. Open the main UI menu
4. Click the `Renew token`
5. See the query completed but the spinner spins

**Expected behavior**

It should stop spinning after the request returned

**Environment:**

* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.8.2
Storage Type    s3
Cluster Name    <redacted>
Cluster ID      <redacted>
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`): `Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)`
* Server Operating System/Architecture: ubuntu focal 20.04

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Hi! Thanks for the bug report. This has been fixed in 1.8 and will be backported to 1.7. Appreciate the effort!

**Comment by zerkms** [comment]
@hsimon-hashicorp what version was it fixed? It's still reproducible in 1.8.5 (released 5 days ago)
