### ISSUE TITLE
On Restart - Error initializing storage of type raft: failed to create fsm: failed to open bolt file: timeout

### ISSUE THREAD

**Issue by Goobaroo** [hashicorp/vault#15197]
**Describe the bug**
We have a vault set running in our GKE cluster.  Lately we've been having an issue where our first instance vault-0 is unable to start up.  After around 16 restarts the pod finally recovered.  But when it is failing we are getting the following error.

> Error initializing storage of type raft: failed to create fsm: failed to open bolt file: timeout

I've seen this same issue when running a 3 member cluster under minikube.

**To Reproduce**
1. Restart the pod

**Expected behavior**
I expect the pod to startup cleanly.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.9.2 ('f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf') (cgo)
* Server Operating System/Architecture: GKE

Vault server configuration file(s):

```hcl
disable_mlock = true
seal "gcpckms" {
  project     = "<scrubbed>"
  region      = "<scrubbed>"
  key_ring    = "<scrubbed>"
  crypto_key  = "<scrubbed>"
}
ui = true
listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  telemetry {
    unauthenticated_metrics_access = "true"
  }
  tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
  tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
}

storage "raft" {
  path = "/vault/data"
  retry_join  {
    leader_api_addr = "https://vault-0.vault-internal.score-vault.svc.cluster.local:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
    leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
    leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  }
  retry_join  {
    leader_api_addr = "https://vault-1.vault-internal.score-vault.svc.cluster.local:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
    leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
    leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  }
  retry_join  {
    leader_api_addr = "https://vault-2.vault-internal.score-vault.svc.cluster.local:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
    leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
    leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  }
  retry_join  {
    leader_api_addr = "https://vault-3.vault-internal.score-vault.svc.cluster.local:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
    leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
    leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  }
  retry_join  {
    leader_api_addr = "https://vault-4.vault-internal.score-vault.svc.cluster.local:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
    leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
    leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  }
}

service_registration "kubernetes" {}

telemetry {
  prometheus_retention_time = "30s",
  disable_hostname          = true
}
```

**Additional context**
We've also noticed that 3 of our 5 pods have 660 permissions on the vault.db file when we expected them to have 600.

**Comment by kBite** [comment]
I noticed the same error after updating Vault from `1.9.2` to `1.10.1`. We're using two config files (1) `config.json` and (2) `storage.hcl`.

In our `vault.service` we combine them like this:
```
ExecStart=/usr/bin/vault server -config=/etc/vault.d/config.json -config=/etc/vault.d/storage.hcl -log-level=info
```
 ```
 # /usr/bin/vault server -config=/etc/vault.d/config.json -config=/etc/vault.d/storage.hcl -log-level=info
Error initializing storage of type raft: failed to create fsm: failed to open bolt file: timeout
...
```
 
 When reversing the order of `-config` options it works:
 ```
 # /usr/bin/vault server -config=/etc/vault.d/storage.hcl -config=/etc/vault.d/config.json -log-level=info
==> Vault server configuration:

             Api Address: ...
             ...
```

This is just a workaround, but maybe it's helping others until the root cause is addressed.

**Comment by Goobaroo** [comment]
That makes me think that it is still an issue and upgrading from our 1.9.2 may not fix it. 

We only have the one config file since it is running in a k8 cluster and picking up the rest of the config through environment variables, no real option to change the order.

- Jason

**Comment by Goobaroo** [comment]
Yes we are using your helm chart.

**Comment by olwe0002** [comment]
I can confirm this error. My usecase:

- k8s cluster with 3 vault pods in ha mode
- auto-unseal is in place
- rekey process was done successfully on the active node
- restarted the 2 standby nodes after that,
 
both standby node restarts fails exactly 2 times with the message `Error initializing storage of type raft: failed to create fsm: failed to open bolt file: timeout`, after that work until the next restart, then fail again the first 2 times

**Comment by AidarGatin** [comment]
Hi, check owner and user for  ...vault/data folder and all *.db inside  like raft.db etc.
`chown -R vault:vault data`  - worked for me!

**Comment by atefhaloui** [comment]
Hi,
Same behaviour with my special build (I've added huaweicloud auto-unseal)[https://github.com/hashicorp/vault/pull/8590#issuecomment-1366106005]:
```
Vault v1.12.2 ('a09715acf12e988a0693d2c068e06afc87d13525'), built 2022-12-28T11:58:46Z

Results:
[ failure ] Vault Diagnose
  [ success ] Check Operating System
    [ success ] Check Open File Limits: Open file limits are set to 1048576.
    [ success ] Check Disk Usage: /vault/audit usage ok.
    [ success ] Check Disk Usage: /dev/termination-log usage ok.
    [ success ] Check Disk Usage: /vault/logs usage ok.
    [ success ] Check Disk Usage: /home/vault usage ok.
    [ success ] Check Disk Usage: /vault/data usage ok.
    [ success ] Check Disk Usage: /vault/config usage ok.
    [ success ] Check Disk Usage: /vault/file usage ok.
    [ success ] Check Disk Usage: /etc/hosts usage ok.
    [ success ] Check Disk Usage: /etc/hostname usage ok.
    [ success ] Check Disk Usage: /etc/resolv.conf usage ok.
  [ success ] Parse Configuration
  [ warning ] Check Telemetry: Telemetry is using default configuration
    By default only Prometheus and JSON metrics are available.  Ignore this warning if you are using telemetry or are using these metrics and are satisfied with the default retention
    time and gauge period.
  [ failure ] Check Storage: Diagnose could not initialize storage backend.
    [ failure ] Create Storage Backend: Error initializing storage of type raft: failed to create fsm: failed to open bolt file: timeout
```
I've added an initcontainer but I still got the error:
```yaml
  extraInitContainers:
    - name: chmod
      image: "alpine"
      command: [sh, -c]
      args:
        - if [ -f /vault/data/vault.db ]; then echo "Updating file permissons ..."; chmod 600 /vault/data/vault.db /vault/data/raft/raft.db; fi
      volumeMounts:
        - name: data
          mountPath: /vault/data/
```

**Comment by Goobaroo** [comment]
> 

Makes no difference, the files are already owned by vault and 660

**Comment by maxb** [comment]
> I have no clue on why I have the error when issuing the diagnose command.

It is normal to receive this error from diagnose, if you run diagnose whilst the Vault server process is running. To get a clean diagnose report it would need to be run with the Vault server stopped (which can be tricky to achieve in Kubernetes environments).

**Comment by ayk33** [comment]
I'm experiencing the same issue on vault 1.8.4. On restart of a vault pod the pods get stuck in crashloop for a little bit and eventually go healthy.

**Comment by Goobaroo** [comment]
We found out that the storage is too slow backing the PVC.  The timeout for opening the raft DB is 1s, that needs to be parameterized.

We added to our chart a pre DD action to cache the raft DB in the pod and that resolved the load error. 

```yaml
      containers:
      - args:
        - |
          cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
          [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
          [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
          [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
          [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
          [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
          [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
          time dd if=/vault/data/vault.db of=/dev/null;
          /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl -log-level=trace - --enable-auto-unseal
```

**Comment by kayumiman** [comment]
I Fixed this issue, by creating a new vault/data and then I copied my old data vault.db and raft.db into them.

**Comment by Goobaroo** [comment]
> I Fixed this issue, by creating a new vault/data and then I copied my old data vault.db and raft.db into them.

That is likely the same fix, of pre-loading the data into memory.  The issue still remains of a slow disk could take more than 1s to open the database files.

**Comment by bhatikuldeep** [comment]
I fixed this issue by using storage raft path as 

```
storage "raft" {
  path    = "/opt/vault/data"
}
```

For more information 
- https://developer.hashicorp.com/vault/tutorials/day-one-raft/raft-deployment-guide?in=vault%2Fday-one-raft
- https://discuss.hashicorp.com/t/vault-raft-aws-tls-bolt-file-error/17132/5
- https://www.42.mach7x.com/2020/08/11/error-initializing-storage-of-type-raft-failed-to-create-fsm-failed-to-open-bolt-file-open-home-vault-data-vault-db-permission-denied/

**Comment by heatherezell** [comment]
Thanks for the report! This issue was filed against Vault `v1.9.2`, which is no longer a supported release.

We're unable to investigate bugs against unsupported versions. If you're still experiencing this on a current supported release of Vault, please open a new issue with updated environment details and we'll take a look.

For a list of currently supported versions, see the [Vault version support page](https://github.com/hashicorp/vault/blob/main/.release/versions.hcl). For Enterprise long-term support information, see the [LTS tracker](https://developer.hashicorp.com/vault/docs/updates/lts-tracker).
