### ISSUE TITLE
Unclear HTTP API documentation - (status code section)

### ISSUE THREAD

**Issue by boncheff** [hashicorp/vault#276]
Under HTTP Status Codes we have the following:

`400 - Invalid request, missing or invalid data. See the "validation" section for more details on the error response.`

Where exactly is the `validation` section in the docs?

**Comment by karel1980** [comment]
It looks like there isn't one... It's both in api/SPEC.md and in the website docs. As far as I can see there aren't any 400 responses being sent explicitly by vault. I think it may be more of a placeholder for future behaviour.

**Comment by boncheff** [comment]
@karel1980 is it worth making that clear in the docs to help people like myself in the future?

**Comment by karel1980** [comment]
By bad, there are plenty of 400 responses being sent; I only grepped for '400', but they're sent using the constant `http.StatusBadRequest`. Usually these are accompanied by the underlying errors in the response body. As far as I can see the resolution of this issue is to either remove the reference to the "validation" section or to add one. The validation section should list only list very generic/common errors (like malformed json in the request body, ...). More specific errors (e.g. invalid keys) should only be documented on the relevant api call.

**Comment by armon** [comment]
I think the mistake is just that there is no "validation" section. It is a documentation bug.

**Comment by boncheff** [comment]
Fixed in PR 89a75ba

**Comment by Naktibalda** [comment]
I still see a reference to validation section in https://www.vaultproject.io/api/index.html
