### ISSUE TITLE
Imported ed25519 private key into vault secrets transit engine fails when calling sign endpoint

### ISSUE THREAD

**Issue by Ruddickmg** [hashicorp/vault#30665]
**Describe the bug**
When I try to use a private ed25519 key that has been imported into vault via the import endpoint it causes vault to panic. 

**To Reproduce**
1. Generate a private key (I have tried various methods, but this is a simple example)
  - openssl genpkey -algorithm Ed25519 -out private_key.der -outform DER

2. Import key into vault in any way (I have tried both the manual and using the helper function)
   - vault transit import transit/keys/my-key "$(cat private_key.der | base64)" type="ed25519" derived=true
   - this step succeeds!

3. try to sign data with imported key
   - vault write transit/sign/my-key input="$(cat hello | base64)" context="$(cat world | base64)"

   - Error writing data to transit/sign/c: Put "http://127.0.0.1:8400/v1/transit/sign/c": EOF
 
5. see logs
   - http: panic serving 127.0.0.1:46414: ed25519: bad private key length: 32

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.19.0
* Vault CLI Version (retrieve with `vault version`): v1.19.0
* Server Operating System/Architecture:
  - linu x86 (ubuntu latest) running in docker v27.3.1
  - and arm7 (nixos latest) running in k3s v1.32.0,

Vault server configuration file(s):

for my local running in docker
```hcl
listener "tcp" {
  address = "0.0.0.0:8400"
  tls_disable = true
}
```

for my remote server running on k3s
```hcl
       cluster_name = "vault-integrated-storage"
listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_cert_file = "/vault/userconfig/tls-server/tls.crt"
  tls_key_file = "/vault/userconfig/tls-server/tls.key"
}

seal "transit" {
  address = "https://vault-unseal.vault-unseal.svc.cluster.local:8200"
  disable_renewal = "false"
  key_name = "autounseal"
  mount_path = "transit/"
  tls_skip_verify = "false"
  tls_server_name = "vault-unseal"
  tls_ca_cert = "/vault/userconfig/tls-ca/ca.crt"
  tls_client_cert = "/vault/userconfig/tls-server/tls.crt"
  tls_client_key = "/vault/userconfig/tls-server/tls.key"
}

storage "raft" {
  path = "/vault/data"
  retry_join {
    leader_api_addr = "https://vault-0.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
  }
  retry_join {
    leader_api_addr = "https://vault-1.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
  }
  retry_join {
    leader_api_addr = "https://vault-2.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
    leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
    leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
  }
  autopilot {
    server_stabilization_time = "10s"
    last_contact_threshold = "10s"
    min_quorum = 2
    cleanup_dead_servers = true
    dead_server_last_contact_threshold = "10m"
    max_trailing_logs = 500
    disable_upgrade_migration = false
  }
}
```

**Comment by mwmahlberg** [comment]
You should link this in [your SF question](https://serverfault.com/questions/1181426/how-can-i-import-an-ed25519-private-key-into-vault-transit-secrets-engine-for-te?noredirect=1#comment1538719_1181426).

**Comment by heatherezell** [comment]
Hi there - can you provide more logs for this? Thanks!

**Comment by Ruddickmg** [comment]
> Hi there - can you provide more logs for this? Thanks!

Updated question with full log output

**Comment by tchernobog** [comment]
I am seeing the same after update to 1.20.2 from 1.17.x. We needed to roll back to a backup.

**Comment by Ruddickmg** [comment]
This actually appears to be fixed for me in the latest version (1.20.2) (using the vault docker container). Odd that it is not working for others 🤔

**Comment by Ruddickmg** [comment]
The main thing I am trying to achieve is testing my application's integration with Vault via the Vault docker container. The two issues I have found/mentioned make it impossible. I need a public key to test against, which AFAIK can only be achieved by:

1. Creating a public & private key pair and importing the private key (failing due to the errors above), or
2. Retrieving the public key from vault (vault does not return the public key as expected/[detailed in the Vault transit documentation](https://developer.hashicorp.com/vault/api-docs/secret/transit#read-key))

Is this something people don't usually test integration for? Wondering if I'm doing something silly/wrong since there don't seem to be a lot of other people having issues with this.

**Comment by tchernobog** [comment]
(seems a fix was committed as part of c19829ccd7ab6c52bf5772e4977262d0cb1e43eb)

**Comment by tchernobog** [comment]
@rculpepper seems the issue is still present and not fixed with the new release. The following python snippet will show clearly the regression:

```python
#!/usr/bin/env python3

# you need testcontainers installed: e.g. `pip install testcontainers`

import base64
import hashlib
import requests
from testcontainers.vault import VaultContainer

# VERSION_TO_TEST = "1.18.4" # this version is fine
VERSION_TO_TEST = "1.20.4" # this version has the issue

with VaultContainer(f"hashicorp/vault:{VERSION_TO_TEST}") as vault:
    base_url = vault.get_connection_url() + "/v1"
    headers = {"X-Vault-Token": vault.root_token, "Content-Type": "application/json"}
    requests.post(f"{base_url}/sys/mounts/transit", json={"type": "transit"}, headers=headers)

    # Create ed25519 key
    requests.post(f"{base_url}/transit/keys/test-key", json={"type": "ed25519"}, headers=headers)

    # Try to sign with key
    text = b"This text should be signed"
    digest = base64.b64encode(hashlib.sha512(text).digest()).decode('ascii')

    response = requests.post(
        f"{base_url}/transit/sign/test-key",
        json={"prehashed": True, "input": digest, "hash_algorithm": "sha2-512"},
        headers=headers
    )

    print(f"Status: {response.status_code}")
    print(f"Response: {response.json()}")
```

Just switch between the two versions (1.18.4 passes, 1.20.4 fails). Could you please reopen the ticket? I would like to avoid creating a new one. I was also able to reproduce this by creating the key directly in the Vault, without importing it from an external source.

**Comment by Ruddickmg** [comment]
Can confirm this still does not work for the current release (1.20.4)

**Comment by tchernobog** [comment]
At the end, I decided to open https://github.com/hashicorp/vault/issues/31574 due to lack of a response.
