### ISSUE TITLE
Cassandra endpoint configuration impossible

### ISSUE THREAD

**Issue by mkulikk** [hashicorp/vault#3370]
**Environment:**

* Vault Version: 0.8.1
* Operating System/Architecture: CentOS 7.3

**Expected Behavior:**
Configuring cassandra endpoint returns 204 after issuing command:
curl -i -X POST -H "Content-Type: application/json" -H "X-Vault-Token: XXX" http://localhost:8200/v1/cassandra/config/connection -d '{"hosts":"127.0.01:9042","username":"abc","password":"def","protocol_version":4}'

In return I should get 204

**Actual Behavior:**
Getting message = "Error creating session: no connections were made when creating the session"
Status code = 400

**Steps to Reproduce:**
Compile vault 0.8.1 with golang 1.8 or 1.9

**Comment by ror6ax** [comment]
Seems to be related to https://github.com/gocql/gocql/issues/946

**Comment by ror6ax** [comment]
@jefferai - would Vault 0.8.1 work with the older gocql? People in related issue seem to find error starts after https://github.com/gocql/gocql/commit/77431609f517cb41ee9afdcdd373561c4d935316 

This blocks me & @mkulikk in a pretty bad way, we're looking for a fast workaround before proper fix.

**Comment by chrishoffman** [comment]
We ran into this in testing and I believe it was fixed in 0.8.3.  Are you able to test it out with that version of Vault?

**Comment by mkulikk** [comment]
Tested with vault 0.8.3 compiled with golang 1.9 (1.8 was causing errs). Still fails with the same error

**Comment by ror6ax** [comment]
@chrishoffman what changes in Vault are to tackle this problem? I was under the impression it's transitive issue to gocql, is it not?

**Comment by chrishoffman** [comment]
Check out #3296.  I know we referenced the linked issue at some point while addressing the issue.  Maybe @calvn can also provide more context.

**Comment by calvn** [comment]
@ror6ax I think there is an issue with gocql parsing the ports that are provided as part of the hosts into its keyring. Try passing in port explicitly, which will set the cluster config's/session's port to the value provided. 

The only issue that you might encounter with this is if your cassandra nodes within the cluster exposes different ports as part of its listen_address/broadcast_address (since it will use the same port for all nodes when connecting). I didn't dig too deep into gocql's source code, but it's probably worth bringing this up to gocql/gocql#946 if this is indeed the problem.

**Comment by ror6ax** [comment]
We are passing the url as shown before - `hosts":"127.0.01:9042`
I'm not sure what do you mean by "pass port explicitly".

**Comment by calvn** [comment]
#3296 added the option to pass the port explicitly as part of the payload/CLI flag.

```
'{"hosts":"127.0.01:9042","port": 9042,"username":"abc","password":"def","protocol_version":4}'
```

**Comment by ror6ax** [comment]
Aha! It's not in the docs yet, afaik.

**Comment by calvn** [comment]
It should be :) https://www.vaultproject.io/api/secret/databases/cassandra.html#port

**Comment by ror6ax** [comment]
Out of curiosity, have you guys ever considered setting up Travis CI integration test run to verify things like these? With Cassandra and other external resources set up in Docker containers as resources? We have that internally using our own CI, I'd be happy to make a PR with one working for externally, here.

**Comment by calvn** [comment]
Were you able to get around the issue by providing the port explicitly?

**Comment by ror6ax** [comment]
Just tested. "Error creating session: no connections were made when creating the session" persists with port set explicitly.

**Comment by ror6ax** [comment]
Updated gocql issue with requested CQL queries.

**Comment by calvn** [comment]
@ror6ax can you post the payload (with sensitive info stripped out)? I see that you posted `10.255.11.243` as the broadcast address on that node on the gocql thread, so I just want to make sure that is the address you are providing on the `database/config/cassandra` endpoint. I am not sure if you are on the same team as @mkulikk , but he is using `cassandra/config/connection` which is the deprecated backend/endpoint.

**Comment by jefferai** [comment]
Closing due to lack of response.
