### ISSUE TITLE
New Line in `allow_subdomains` Leads to Stacktrace

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#454]
This probably affects parsing of other variables too if they aren't strings, but a stray `\n` (even at the end) in the `allow_subdomains` variable when creating a PKI role leads to a Go stacktrace.  I wouldn't want my secure Vault to stacktrace too often, so I thought I should report this:

```
2015/07/23 17:41:35 http: panic serving 172.16.3.14:40613: error reading allow_
subdomains: cannot parse '' as bool: strconv.ParseBool: parsing "true\n": inval
id syntax
goroutine 37 [running]:
net/http.func·011()
        /Users/armon/go/src/net/http/server.go:1130 +0xbb
```

**Comment by ctennis** [comment]
Fixed in https://github.com/hashicorp/vault/pull/503

**Comment by sethvargo** [comment]
@ctennis I don't think it's fair to say that #503 "fixes" this. It certainly prevents the panic, but the underlying issue still exists. I think we should fix that issue :smile:

**Comment by ctennis** [comment]
@sethvargo Forgetting the implementation of the patch, the end result should still still be the same right, that the user gets an error for bad input vs. a panic condition?

**Comment by armon** [comment]
I think this is fixed by the latest PR @ctennis sent
