### ISSUE TITLE
Github auth is not leased and does not ever check for changes

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#652]
It appears that the Github auth module does not check for changes.  Once the token is generated, it appears to not expire, nor is anything ever re-checked.  I revoked my token in Github and I still have access to vault days later.  Presumably this also means that if I remove someone from the org entirely or just from the group that is granting them a certain policy, that is never re-checked either, though I haven't yet tested that.

This seems like a pretty big security gap.  I don't think users would expect that if they authenticated with Github that revoking a key that might be compromised (or just for good key rotation measures) wouldn't revoke that access.  And even more seriously, if someone leaves our company, or changes roles and we want to revoke their vault access, it does not appear that there is any way to do this.

Adding a lease for the Github auth would certainly help here, though that will be a bit more of a pain for users.  The ideal state would be if Vault kept the Github token associated with the Vault auth token and periodically re-checked it.  However, for fixing the security issue in the short term, just adding a lease would be a huge improvement.

**Comment by sethvargo** [comment]
@bkrodgers the tokens themselves expire in Vault though. If this is something you're concerned about, you should set a low TTL value on the auth endpoint for github so that their tokens expire in a short period of time. You can also revoke the entire tree if someone leaves the company, which will revoke any secrets and access the user had.

The GitHub auth does have a lease associated with it, and when that lease expires, all tokens are revoked. Are you experiencing different behavior?

**Comment by bkrodgers** [comment]
The tokens vault issues from the Github backend do not expire from my experience with 0.2.  I haven't tried 0.3 yet.  I've had the same token -- on a now revoked Github token -- since last Thursday.

I didn't see documentation on how to set a TTL for the Github auth backend.  Not discounting that I might be missing it.

**Comment by jefferai** [comment]
The GitHub auth backend does not currently allow specifying the TTL when logging in. In 0.2 this means it will use the system default lease TTL (which IIRC is 7 days, and thus would not currently be expired). In 0.3 it will use, in order, the mount configured default TTL, or, if there is none set, the system default TTL. Both of those are settable. See the `mount-tune` command for setting the per-mount value.

**Comment by bkrodgers** [comment]
Gotcha.  So it sounds like 0.3 will allow me to specify a default and max TTL for the github mount point, which will then give me what I need to at least expire the tokens after a period of time.  I still think it'd be beneficial to keep the underlying github token and periodically recheck it, which would allow setting a longer expiration time.  As it is, I'll need to set that pretty short (no more than 24 hours) to ensure access gets revoked.

Someone else on my team (@larryboymi) was curious about this issue and was looking at the source.  He noticed that there's a special case for the root policy.  It looks like it does not apply the default TTL.  Why is that?  

https://github.com/hashicorp/vault/blob/4d16d5716d8086ba277c5d890a6ff5e3fd716895/vault/core.go#L548

**Comment by larryboymi** [comment]
Well I was saying that the source indicated that if the policy was set to root and TTL is 0, to not override it with the default. Perhaps this is due to not wanting to expire the root secret?

```go
// Set the default lease if non-provided, root tokens are exempt
if auth.TTL == 0 && !strListContains(auth.Policies, "root") {
	auth.TTL = sysView.DefaultLeaseTTL()
}

**Comment by jefferai** [comment]
Correct -- root tokens do not expire.

**Comment by larryboymi** [comment]
The only issue I see with that is when folks set the policy to ```root``` for what's really not a root token. But hopefully they're doing this realizing some things in the code are making specific decisions based on that special policy.

**Comment by bkrodgers** [comment]
Right, there's a distinction between the root policy and the root token.  This code is applying it to the root policy, yet even the comment refers to the intent to be to hit the root token.

You might be thinking "you shouldn't use the root policy outside of the root token!"  The reason I want to do that is so that I can delegate admin access and not have to share that root access token among multiple people.  I basically want to stick that root token in an (actual) vault and never use it once I've setup the delegation group.   Additionally, this way any actions performed by a given admin are logged in the audit log with their github ID so I know which admin performed them.  I suppose I could create a policy that isn't root but gives sudo access to all paths needed to admin things rather than using the actual root policy, but one way or another I want to have a root (or "virtual root") level access I can give out this way and minimize use of the single root token.

**Comment by larryboymi** [comment]
I think we should move away from the root policy for shared secrets

Sent on the new Sprint Network

----- Reply message -----

**Comment by jefferai** [comment]
It is generally recommended not to have the `root` policy applied to any tokens that are not not meant to be actual root tokens -- because having that policy *makes* them root tokens!

Vault is a zero-trust system. Adding a policy with `sudo` access to all the required things may be annoying, but it's also a declarative way to ensure that nothing is ever accessed that wasn't specifically allowed.

**Comment by vishalnayak** [comment]
Fixed by #664

**Comment by bkrodgers** [comment]
Question on the fix for this.  My understanding is that renewing an auth token simply renews it.  It still doesn't re-check anything against the vault back end.  In other words, if I allow github tokens to be renewable, I still have a problem in that a token could be renewed forever, even after the underlying github access has been removed, so long as they renew it before the lease has expired?  

I think the more secure way to make github tokens renewable is to store the actual github token in vault, so that on renew it can re-check both the org and team membership.  Otherwise, someone who once had access legitimately but has been revoked, and is now a bad actor (i.e., fired and pissed off) can just setup a script to run for (ttl - 1) and continually renew their token forever, right?    

In the meantime, I think I want a TTL on the lease, but I don't want it to be renewable.  It'll be a pain for developers to need to re-enter their token every few hours vs just doing a token renew, but it seems like this is a better way to ensure access gets revoked within (ttl) time of a user's membership in a given team or our overall org is removed.  My question is how do I do this?  It looks like at the github auth config level, if I specify a TTL > 0, it defaults to a renewable lease.  

It looks like in order to get a TTL but have non-renewable tokens, I actually need to leave the ttl settings at the github auth config level at 0, and then set a TTL on the github auth *mount* using mount-tune.  Is this right?  If so, that's a bit confusing and not obvious.  I only found out because I ended up in this state by accident while trying to set things up right (using mount tune before I used auth/github/config) and noticed my tokens weren't coming back as renewable (before I realized that's what I want).  You may want to at a minimum update the docs, or add the ability to explicitly configure if it's renewable on auth/github/config (and for that matter maybe mount-tune too)

**Comment by jefferai** [comment]
> Question on the fix for this. My understanding is that renewing an auth token simply renews it. It still doesn't re-check anything against the auth provider's back end. In other words, if I allow github tokens to be renewable, I still have a problem in that a token could be renewed forever, even after the underlying github access has been removed, so long as they renew it before the lease has expired?

Correct.

> I think the more secure way to make github tokens renewable is to store the actual github token in vault, so that on renew it can re-check both the org and team membership. Otherwise, someone who once had access legitimately but has been revoked, and is now a bad actor (i.e., fired and pissed off) can just setup a script to run for (ttl - 1) and continually renew their token forever, right?
...
> It looks like in order to get a TTL but have non-renewable tokens, I actually need to leave the ttl settings at the github auth config level at 0, and then set a TTL on the github auth mount using mount-tune. Is this right? If so, that's a bit confusing and not obvious. I only found out because I ended up in this state by accident while trying to set things up right (using mount tune before I used auth/github/config) and noticed my tokens weren't coming back as renewable (before I realized that's what I want). You may want to at a minimum update the docs, or add the ability to explicitly configure if it's renewable on auth/github/config (and for that matter maybe mount-tune too)

Unfortunately you're basically right about all of this (although a fired employee probably shouldn't have network access to Vault, regardless of whether their token is still valid). The good news is that we know that there are pain points in the way many backends work right now, especially since some of them treat things like TTL rather differently than others. We're actively planning to do major standardization efforts that will provide a lot of consistency and provide needed functionality (for instance, separating renewability from whether there is a requested TTL). But, it's going to take some time. If I had to guess, the major under-the-hood code will happen in 0.5 and the majority of the backends will see upgrades to new versions in 0.6 that implement the new interfaces and APIs.

**Comment by jefferai** [comment]
@bkrodgers I've filed #754 to keep track of the idea of storing GitHub tokens in the backend to re-check for membership. If an interested party wants to work on this functionality ahead of time, that would be great...we'll use the other ticket to track it.

**Comment by bkrodgers** [comment]
Fantastic, thanks!  If I get a few moments I also may send you a PR to add a few notes about this to the docs, since it's not totally obvious.
