### ISSUE TITLE
SSH CA permit other algorithm than rsa sha1

### ISSUE THREAD

**Issue by tgerbier** [hashicorp/vault#8414]
**Description**
Since openssh released openssh 8.2, it as deprecated ssh-rsa with SHA1 which was the default.
See https://www.openssh.com/releasenotes.html. 
When using the vault ssh CA to authentify host_key (but I guess the trouble is the same for client certificats) ssh client refuse to use the rsa sha1 certificate.
Searching in the API vault ssh, it does not seem that there is option or choice to have another algorithm than ssh-rsa (SHA1).

**To Reproduce**
1. Setup a vault ssh CA
2. use it via `@cert-authority *.yourdomain.org ssh-rsa AAAaaa....` in the client `known_hosts` 
3. See ssh >= 8.2 complaining : ```check_host_cert: certificate signature algorithm ssh-rsa: signature algorithm not supported
The authenticity of host '*******' can't be established.```

**Expected behavior**
As suggested in the openssh release notes, to have at least a better default algorithm, or better being able to choose one.

**Environment:**
* Vault Server Version : 1.2.3
* Vault CLI Version (retrieve with `vault version`): v1.3.2
* Server Operating System/Architecture: Ubuntu/bionic

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "127.0.0.1:*****"
  path = "vault"
}

listener "tcp" {
  address = "*********:8200"
  tls_cert_file = "/etc/vault/tls/server-bundle.pem"
  tls_key_file = "/etc/vault/tls/server-key.pem"
}

listener "tcp" {
  address = "*********:8200"
  tls_cert_file = "/etc/ssl/certs/server-bundle.pem"
  tls_key_file = "/etc/ssl/private/server-key.pem"
}

cluster_name = "**********"

```

**Comment by tgerbier** [comment]
seems fixed by [this PR](https://github.com/hashicorp/vault/pull/8383)
sorry for the noise.

**Comment by catsby** [comment]
Hey @tgerbier - thanks for reporting this issue! And no worries about noise, I'm thankful you opened the issue and then followed-up that there's a PR fixing it 😄 

I'll make note of this issue in the PR and leave this issue open until it's addressed. 

Thanks again!

**Comment by Andor** [comment]
@tgerbier I think, Vault should support not only RSA (either sha1 or sha2) but for instance ed25519 as well to choose from. So this issue is still valid even when linked pull request will be merged.

**Comment by evilhamsterman** [comment]
ed25519 is also more secure and shorter than RSA keys and is fast becoming the recommended option for SSH.

**Comment by axi92** [comment]
I don't know how insecure this workaround is but you can enable the ssh-rsa in you openssh server again until the vault patch is released.
https://man.openbsd.org/sshd_config#CASignatureAlgorithms

**Comment by andreaso** [comment]
So, with https://github.com/hashicorp/vault/pull/9096 included in the newly released Vault 1.4.3 it's now possible to create certs with RSA-SHA2 signatures.

I've created the https://github.com/terraform-providers/terraform-provider-vault/pull/809 PR to be able to use the new `algorithm_signer` argument with the Terraform Vault provider.

**Comment by JDiprose** [comment]
I'm not sure whether its appropriate to tag the below to this issue, but I think a bit of the code relating to this work prevents ca keys other than of type ssh-rsa being used.

I can uploaded externally-generated 521-bit ecdsa ca keys into ssh/config/ca but when I try to sign with them I get and HTTP500 with error message 'failed to generate signed SSH key: sign error', from your path_sign.go line 538.

Lines 532-536 of your path_sign.go:

  https://github.com/hashicorp/vault/blob/master/builtin/logical/ssh/path_sign.go#L532

	algo := b.Role.AlgorithmSigner
	if algo == "" {
		algo = ssh.SigAlgoRSA
	}
        sig, err := sshAlgorithmSigner.SignWithAlgorithm(rand.Reader, certificateBytes, algo)

I think that the sshAlgorithmSigner.SignWithAlgorithm call on line 536 ends up in golang's keys.go line 967:

  https://github.com/golang/crypto/blob/ab33eee955e00ff7c973405b2780aca48d293014/ssh/keys.go#L967

As 'algo' has been forced to be an rsa-type AlgorithmSigner, ca keys not of type rsa will fail the condition check on 987 and be kicked back with an error message on 988. To pass that condition check 'algo' must be an empty string or the key type. I can't configure it to be the key type due to the condition check in path_roles.go line 483-487:

  https://github.com/hashicorp/vault/blob/99564f52d0e570719050ab80326bb91c25188160/builtin/logical/ssh/path_roles.go#L483

The simplest solution would appear to be to remove lines 533-535 from your path_sign.go in order to allow 'algo' to be an empty string, and let golang's keys.go handle the selection of the default.

Sorry, I'd test etc but I don't know how.

**Comment by madjam002** [comment]
> Still having this issue with an old vault migrated to vault v1.8.2 What is the migration procedure here?

https://www.vaultproject.io/api/secret/ssh#algorithm_signer

Switch to `rsa-sha2-256` or `rsa-sha2-512` in your SSH secret engine roles.

**Comment by con-f-use** [comment]
Thank you, the quick help is really appreciated. But do I really have to repeat every single option that is already set for the existing role in that `vault write`? I'd assume there is an "update".

```console
$ vault read ssh/roles/all
Key                            Value
---                            -----
algorithm_signer               n/a
allow_bare_domains             false
allow_host_certificates        true
allow_subdomains               true
allow_user_certificates        true
allow_user_key_ids             false
allowed_critical_options       n/a
allowed_domains                *
allowed_extensions             permit-X11-forwarding,permit-agent-forwarding,permit-port-forwarding,permit-pty,permit-user-rc
allowed_user_key_lengths       map[]
allowed_users                  *
allowed_users_template         false
default_critical_options       map[]
default_extensions             map[permit-X11-forwarding: permit-agent-forwarding: permit-port-forwarding: permit-pty: permit-user-rc:]
default_extensions_template    false
default_user                   main
key_bits                       0
key_id_format                  n/a
key_type                       ca
max_ttl                        720h
ttl                            30h
$ vault write ssh/roles/all algorithm-signer="rsa-sha2-256"
Error writing data to ssh/roles/all: Error making API request.

URL: PUT https://subdomain.domain.top:8200/v1/ssh/roles/all
Code: 400. Errors:

* missing key type
```

**Comment by con-f-use** [comment]
Yeah well, I'm not gonna learn and setup Terraform in my setup. However, what did work:

```console
$ vault read ssh/roles/all -format=json \
    | jq -r .data | sed -E '/algorithm_signer/ s/"",/"rsa-sha2-512",/'  \
    | vault write ssh/roles/all -
Success! Data written to: ssh/roles/all
```
