### ISSUE TITLE
TestCore with KV v2 doesn't generate metadata

### ISSUE THREAD

**Issue by glindstedt** [hashicorp/vault#8440]
**Describe the bug**

While using the `TestCore` in the testing module to write integration tests, and mounting a KV v2 key-value store, it seems like it does not behave the same as a proper vault deployment, unless I'm missing some fundamental part of the setup process. Normally when creating a secret through the HTTP api under `kv/data/test` a matching metadata entry would get created under `kv/metadata/test`, however this does not seem to happen when using `TestCore`.

**To Reproduce**

This test displays the issue:

```go
package test

import (
	"testing"

	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/http"
	"github.com/hashicorp/vault/vault"
)

func Test(t *testing.T) {
	core, _, rootToken := vault.TestCoreUnsealed(t)
	_, addr := http.TestServer(t, core)
	c, _ := api.NewClient(api.DefaultConfig())
	c.SetAddress(addr)
	c.SetToken(rootToken)

	// Create KV V2 mount
	c.Sys().Mount("kv", &api.MountInput{
		Type: "kv",
		Options: map[string]string{
			"version": "2",
		},
	})

	c.Logical().Write("kv/data/test", map[string]interface{}{
		"data": map[string]interface{}{
			"hello": "world",
		},
	})

	// Read secret data
        // Output: map[hello:world]
	secret, _ := c.Logical().Read("kv/data/test")
	t.Error(secret.Data["data"])

	// Read secret metadata
        // Output: <nil> <nil>
	secretMeta, err := c.Logical().Read("kv/metadata/test")
	t.Error(secretMeta, err)
}
```

**Expected behavior**

That the appropriate metadata entry would be created with the new secret.

**Environment:**

* Go 1.14
* vault api 1.3.2

**Comment by catsby** [comment]
Hello - 

`TestCoreUnsealed` doesn't use the regular `KV` backend, instead it uses a `PassthroughBackend` to essentially mock the kv behavior. `TestCoreUnsealed` leads to `TestCoreWithSeal`:

https://github.com/hashicorp/vault/blob/6c4508007a79567d6c8c1ca4e1424b1d54d46aa7/vault/testing.go#L125-L133

There, a `CoreConfig` is created that does not define any `LogicalBackends`. By the time the new core is created in `NewCore`, a default, passthrough kv is added:

https://github.com/hashicorp/vault/blob/17361f2b5a3599a2d8ff6427524fe54fced47e89/vault/core.go#L881-L888

Contrast that with something like `testVaultServerUnseal`:

https://github.com/hashicorp/vault/blob/17361f2b5a3599a2d8ff6427524fe54fced47e89/command/command_test.go#L83-L97

That setups an unsealed vault cluster configured with a normal KV backend defined here:

https://github.com/hashicorp/vault/blob/17361f2b5a3599a2d8ff6427524fe54fced47e89/command/command_test.go#L41-L47

That core config eventually gets used in `vault.NewTestCluster`:

https://github.com/hashicorp/vault/blob/6c4508007a79567d6c8c1ca4e1424b1d54d46aa7/vault/testing.go#L1100

Granted that `testVaultServerUnseal` is a private method, you could look to some of our other tests that use `NewTestCluster`, for example the pki backend here:

https://github.com/hashicorp/vault/blob/6c4508007a79567d6c8c1ca4e1424b1d54d46aa7/builtin/logical/pki/ca_test.go#L28-L42

The factory function is defined inline there, but for KV you'd want to reference the KV factory defined in that plugin:

https://github.com/hashicorp/vault-plugin-secrets-kv/blob/3541c91333def6240e4e2640adc3c9e7bf13f409/backend.go#L73-L91

Unfortunately in the end `TestCoreUnsealed` isn't documented to have this limitation 😦 I admit I had to do some digging and asking around to discover what was (not) happening here. For testing Vault backends or integrations, I would use `NewTestCluster`. 

Hopefully this addresses your questions!

**Comment by glindstedt** [comment]
@catsby Thank you for the really thorough answer!

I've successfully refactored my tests to use `NewTestCluster` instead and it works like a charm. Really appreciate that you showed all the code snippets, it gave insight into how things fit together and helped with the migration.

I assume you might want to keep the issue around to maybe get some documentation about the limitation in `TestCoreUnsealed`, but in my case at least the issue is resolved.

**Comment by catsby** [comment]
Thanks for following up, @glindstedt. I'll leave this open as you suggest, I'm not honestly sure why `TestCoreUnsealed` functions the way it does. Generally though, `NewTestCluster` seems to be the better option, so I'm glad you were able to get that working.

**Comment by mwodrich** [comment]
I figure since I just ran headlong into this issue myself that I’d like to thank you both for documenting and explaining this issue, and that I should stand up and be counted as another person this affects.

I was writing tests to verify that I was working appropriately with versioned KV v2 data when I found that the responses from the TestCoreUnsealed server contained my data, but were structurally unlike the documented responses.

In terms of alternatives to TestCoreUnsealed, upon discovering testVaultServerUnseal in the code, I was excited when I saw how straightforward it was to use testVaultServerUnseal in the command tests and then immediately crestfallen when I realized it was only defined in the test file and not exported.  I think it would be very cool if that could become accessible to folks writing tests since it so elegantly provides the needed test server.

I thought I’d be able to get by with TestCoreUnsealed, but with this limitation that’s definitely not the case.  +1 to encouraging that it’s limitations should be better documented.  For my part, I’ll also transition my tests over to NewTestCluster along the lines you’ve described.

Thanks again!

**Comment by catsby** [comment]
Thanks for the input @mwodrich , I'm sorry for your troubles. This and other comments have been taken to heart and internally we're discussing and working on improvements to our current tests and tools/methods to improve future testing. I don't have a timeline so please bear with us, but we are working on it 😄

**Comment by innovia** [comment]
> @catsby Thank you for the really thorough answer!
> 
> I've successfully refactored my tests to use `NewTestCluster` instead and it works like a charm. Really appreciate that you showed all the code snippets, it gave insight into how things fit together and helped with the migration.
> 
> I assume you might want to keep the issue around to maybe get some documentation about the limitation in `TestCoreUnsealed`, but in my case at least the issue is resolved.

@glindstedt can  you please provide a sample code, im having a hard time figuring this out

**Comment by glindstedt** [comment]
@innovia Here's the helper function we're using to start the test cluster and add a KV v2 mount:

```go
import (
	kv "github.com/hashicorp/vault-plugin-secrets-kv"
	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/sdk/logical"
	vaulthttp "github.com/hashicorp/vault/http"
	hashivault "github.com/hashicorp/vault/vault"
)

func createVaultTestCluster(t *testing.T) *hashivault.TestCluster {
	t.Helper()

	coreConfig := &hashivault.CoreConfig{
		LogicalBackends: map[string]logical.Factory{
			"kv": kv.Factory,
		},
	}
	cluster := hashivault.NewTestCluster(t, coreConfig, &hashivault.TestClusterOptions{
		HandlerFunc: vaulthttp.Handler,
	})
	cluster.Start()

	// Create KV V2 mount
	if err := cluster.Cores[0].Client.Sys().Mount("kv", &api.MountInput{
		Type: "kv",
		Options: map[string]string{
			"version": "2",
		},
	}); err != nil {
		t.Fatal(err)
	}

	return cluster
}

func TestSomething(t *testing.T) {
    cluster := createVaultTestCluster(t)
    defer cluster.Cleanup()
    rootVaultClient := cluster.Cores[0].Client
    // do your testing
}
```

Hope it helps!

**Comment by innovia** [comment]
@glindstedt  Thank you so much for your help

I tried the code you gave me  but i get 404 on put 

maybe you can spot something here?

```golang

package test

import (
	"testing"

	kv "github.com/hashicorp/vault-plugin-secrets-kv"
	"github.com/hashicorp/vault/api"
	vaulthttp "github.com/hashicorp/vault/http"
	"github.com/hashicorp/vault/sdk/logical"
	hashivault "github.com/hashicorp/vault/vault"
)

type vaultConfigSecret struct {
	path string
	data map[string]interface{}
}

func retrieveSecrets(t *testing.T, client *api.Client, secretsConfigList []string) (map[string]interface{}, error) {
	...
	return secretData, nil
}

func TestVaultSecrets(t *testing.T) {
	cluster := createVaultTestCluster(t)

	testCases := []struct {
		name              string
		secretsConfigList []string
		function          func(*testing.T, *api.Client, []string) (map[string]interface{}, error)
		wants             map[string]interface{}
	}{
		{
			name: "Plain V1 Secret",
			secretsConfigList: []string{
				`{"path": "secrets/v1/some/secrets/path"}`,
			},
			function: retrieveSecrets,
			wants: map[string]interface{}{
				"api_key":      "app_key",
				"database_url": "127.0.0.1:3306",
				"password":     "secret",
			},
		},{
			name: "Plain V2 Secret",
			secretsConfigList: []string{
				`{"path": "secrets/v2/plain/secrets/path/app"}`,
			},
			function: retrieveSecrets,
			wants: map[string]interface{}{
				"api_key":      "app_key_v2",
				"database_url": "v2-host:3306",
				"password":     "secrets-v2",
			},
		},
		{
			name: "secret names as keys v2",
			secretsConfigList: []string{
				`{"path": "secrets/v2/multi/secrets/path/", "use-secret-names-as-keys":  true}`,
			},
			function: retrieveSecrets,
			wants: map[string]interface{}{
				"api_key":      "v2-top-secret",
				"database_url": "v2.mysql.host:3306",
				"password":     "v2-pa33w0rd123",
			},
		},
	}

	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			secretData, err := testCase.function(t, cluster.Cores[0].Client, testCase.secretsConfigList)
			if err != nil {
				t.Fatalf("error running test %s, %v", testCase.name, err)
			}
			if !cmp.Equal(secretData, testCase.wants) {
				t.Logf("wants: %v", testCase.wants)
				t.Logf("got: %v", secretData)
				t.Errorf("secretData = diff %v", cmp.Diff(secretData, testCase.wants))
			}
		})
	}
}

// Setup required secrets, policies, etc.
func seedVaultData(t *testing.T, cluster *hashivault.TestCluster) error {
	var err error
	secretsV1 := []vaultConfigSecret{
		{
			path: "secrets/v1/some/secrets/path",
			data: map[string]interface{}{
				"api_key":      "app_key",
				"database_url": "127.0.0.1:3306",
				"password":     "secret",
			},
		}, 
	}

	secretsV2 := []vaultConfigSecret{
		{
			path: "secrets/v2/plain/secrets/path/app",
			data: map[string]interface{}{
				"api_key":      "app_key_v2",
				"database_url": "v2-host:3306",
				"password":     "secrets-v2",
			},
		},
	}

	log.Info("Seeding secrets into Vault")
	for _, secret := range secretsV1 {
		_, err := cluster.Cores[0].Client.Logical().Write(secret.path, secret.data)
		if err != nil {
			log.Errorf("error seeding secret v1: %v", err)
		}
	}
	for _, secret := range secretsV2 {
		log.Infof("Adding secret %s", secret.path)
		_, err := cluster.Cores[0].Client.Logical().Write(secret.path, secret.data)
		if err != nil {
			log.Errorf("error seeding secret v2: %v", err)
		}
	}

	if err != nil {
		return err
	}

	return nil
}

func createVaultTestCluster(t *testing.T) *hashivault.TestCluster {
	t.Helper()
	t.Log("Creating Vault Test Cluster in-memory backend")

	coreConfig := &hashivault.CoreConfig{
		LogicalBackends: map[string]logical.Factory{
			"kv": kv.Factory,
		},
	}

	cluster := hashivault.NewTestCluster(t, coreConfig, &hashivault.TestClusterOptions{
		HandlerFunc: vaulthttp.Handler,
	})
	cluster.Start()

	// Create KV v1 and v2
	mountInputV1 := &api.MountInput{
		Type: "kv",
		Options: map[string]string{
			"path": "/secrets/v1",
		},
	}

	mountInputV2 := &api.MountInput{
		Type: "kv",
		Options: map[string]string{
			"path":    "/secrets/v2",
			"version": "2",
		},
	}
	mountPath1 := "/secrets/v1"
	mountPath2 := "/secrets/v2"

	log.Info("Creating secrets/v1 kv engine")
	if err := cluster.Cores[0].Client.Sys().Mount(mountPath1, mountInputV1); err != nil {
		t.Fatal("error creating secrets/v1 mount")
	}

	log.Info("Creating secrets/v2 kv engine")
	if err := cluster.Cores[0].Client.Sys().Mount(mountPath2, mountInputV2); err != nil {
		t.Fatal("error creating secrets/v2 mount")
	}

	// Setup required secrets, policies, etc.
	err := seedVaultData(t, cluster)
	if err != nil {
		t.Fatalf("error seeding data: %v", err)
	}

	defer cluster.Cleanup()

	return cluster
}

```

the logs are:

```console
2020-04-18T21:14:55.272-0700 [DEBUG] TestVaultSecrets.core0.core.cluster-listener: performing server cert lookup
2020-04-18T21:14:55.273-0700 [INFO]  TestVaultSecrets.core0.core: enabled audit backend: path=noop/ type=noop
INFO[0002] Creating secrets/v1 kv engine                 source="vault_secret_manager_test.go:215"
2020-04-18T21:14:55.278-0700 [INFO]  TestVaultSecrets.core0.core: successful mount: namespace= path=secrets/v1/ type=kv
INFO[0002] Creating secrets/v2 kv engine                 source="vault_secret_manager_test.go:220"
2020-04-18T21:14:55.281-0700 [INFO]  TestVaultSecrets.core0.core: successful mount: namespace= path=secrets/v2/ type=kv
INFO[0002] Seeding secrets into Vault                    source="vault_secret_manager_test.go:160"
2020-04-18T21:14:55.292-0700 [INFO]  TestVaultSecrets.core0.secrets.kv.kv_1ee4663c: collecting keys to upgrade
2020-04-18T21:14:55.292-0700 [INFO]  TestVaultSecrets.core0.secrets.kv.kv_1ee4663c: done collecting keys: num_keys=1
2020-04-18T21:14:55.292-0700 [DEBUG] TestVaultSecrets.core0.secrets.kv.kv_1ee4663c: upgrading keys: progress=0/1
2020-04-18T21:14:55.292-0700 [INFO]  TestVaultSecrets.core0.secrets.kv.kv_1ee4663c: upgrading keys finished
INFO[0002] Adding secret secrets/v2/plain/secrets/path/app  source="vault_secret_manager_test.go:168"
ERRO[0002] error seeding secret v2: Error making API request.

URL: PUT https://127.0.0.1:64840/v1/secrets/v2/plain/secrets/path/app
Code: 404. Errors:
  source="vault_secret_manager_test.go:171"
INFO[0002] Adding secret secrets/v2/multi/secrets/path/api_key  source="vault_secret_manager_test.go:168"
ERRO[0002] error seeding secret v2: Error making API request.

URL: PUT https://127.0.0.1:64840/v1/secrets/v2/multi/secrets/path/api_key
Code: 404. Errors:
  source="vault_secret_manager_test.go:171"
INFO[0002] Adding secret secrets/v2/multi/secrets/path/database_url  source="vault_secret_manager_test.go:168"
ERRO[0002] error seeding secret v2: Error making API request.
```

**Comment by innovia** [comment]
@glindstedt also tried to disable the v2 secrets creations and test, and i get connection refused (the cluster is not the same port)

```
....

2020-04-18T21:23:39.743-0700 [DEBUG] TestVaultSecrets.core0.core: starting cluster listeners
2020-04-18T21:23:39.743-0700 [INFO]  TestVaultSecrets.core0.core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:0
2020-04-18T21:23:39.743-0700 [INFO]  TestVaultSecrets.core0.core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:64922
...
=== RUN   TestVaultSecrets/Plain_V1_Secret
INFO[0003] secret path secrets/v1/some/secrets/path is a KVv2: false
INFO[0003] Using Vault Secrets
INFO[0003] Getting Vault secrets from path: secrets/v1/some/secrets/path
    TestVaultSecrets/Plain_V1_Secret: vault_secret_manager_test.go:31: Error getting secrets from vault: failed to read secret 'secrets/v1/some/secrets/path' Get "https://127.0.0.1:64919/v1/secrets/v1/some/secrets/path": dial tcp 127.0.0.1:64919: connect: connection refused
```

**Comment by innovia** [comment]
Thanks a lot!  @glindstedt this is extremely helpful!

Its working fine, my mistake for misplacing defer and closing the connection right before i vene started tests.

**Comment by innovia** [comment]
Wanted to add the proper way of setting up a v2 secret

KV version 2 expects the values to be in a Data map: https://www.vaultproject.io/api/secret/kv/kv-v2.html#data

```hcl
secret["data"] = map[string]interface{}{
    "value": pass,
}```

and the path to write the secret must have the `/data` prefix after the secret kv name
`secrets/v2/data/plain/secrets/path/app`

**Comment by HridoyRoy** [comment]
Hi folks,
Seems like this issue has been resolved and just needs some extra documentation around it. Is that right?

**Comment by aphorise** [comment]
@glindstedt any further updates here? - is issue still applicable or anything further pending?

**Comment by hsimon-hashicorp** [comment]
Due to issue age and quiescence, I'm going to go ahead and close this now. Please feel free to re-open as needed. Thanks!
